# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default=datetime.datetime(2018, 6, 20, 8, 19, 45, 952176, tzinfo=utc), max_length=6),
            preserve_default=False,
        ),
    ]
