# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=False),
        ),
    ]
