# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sq',
            field=models.IntegerField(default=False),
        ),
    ]
